spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: consumer
  cloud:
    nacos:
      discovery:
        server-addr: 10.21.32.154:8848

server:
  port: 8081
management:
  endpoints:
    web:
      exposure:
        include: "*"
